### ISSUE TITLE
Fail with error 'UniswapV2Router: INSUFFICIENT_B_AMOUNT'

### ISSUE THREAD

**Issue by rajesh3456** [Uniswap/uniswap-interface#1093]
**Bug Description**
I have tried providing liquidity to pool, i did it so many without any issue, this time my all 4 attempts were failed. I tried wallet exchange transfer it works you can check on my account. please suggest your opinion to resolve, thank you.

**Steps to Reproduce**
1. Go to  my etherscan this is wallet 0xfc3c18709ad20406ef57da950abb8dc6ebf5af36
2. Click on ...
0x994b8972ad5b5a9e8026f02f2af28422ed603d2d2bb849ee502907b5b26d72e8

**Expected Behavior**
I gave gas and also high gwei but still doesn;t work,

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by carbon8d** [comment]
@rajesh3456 - I am having a similar problem, except I am trying to remove from a liquidity pool and receiving the same error.   I have tried a few times and it has failed every single time. Sometimes, I receive the, 'INSUFFICIENT_A_AMOUNT', other times its the ''INSUFFICIENT_B_AMOUNT' but every time I keep losing the GAS fees because it keeps failing. Let me know if you have any better luck.

**Comment by rajesh3456** [comment]
Hey buddy,

I found solution--> just go to setting and set slippage from 1.0% to 5.0%--
this will avoiud transaction failure... the asset you are
swapping/liquidating has high price flactuations..
So, with this you make sure you will get the price with difference than
shown... better than loosing gas :)

THANKS

**Comment by carbon8d** [comment]
@rajesh3456 - Thanks so much! That worked perfectly!
