### ISSUE TITLE
Display liquidity that is locked in staking contracts in the pool page

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1120]

**Comment by litwi1rm** [comment]
I'd like to expand on this issue and potentially the bigger problem. 

There are a ton of people in the liquidity-provider discord channel who don't understand why they can see fees accrued on their liquidity provided for pairs but have no information on liquidity they locked in one of the 4 uni staking contracts. 

To clarify:
When i goto the pools tab I can see the pairs I'm a LP for but do not see my stake in the UNI Liquidity Mining Pool
![image](https://user-images.githubusercontent.com/7134135/94364308-4f45c900-0096-11eb-8cc5-d8b0ba1c3eaf.png)

Further, if I goto "Account analytics and accrued fees". This is where users are really struggling because if you staked 100% of your pool tokens in the "Positions" section it will show $0 liquidity. For people who don't understand they staked their pool tokens in another smart contract to get their free UNI this is concerning.
![image](https://user-images.githubusercontent.com/7134135/94364558-2f170980-0098-11eb-92ef-2455c9555a41.png)

**Comment by djreillo** [comment]
I would also like to expand on this. 

If we go to https://app.uniswap.org/#/uni , we see that the deposited LP tokens in the pool is earning UNI tokens. We have deposited 100% of your LP tokens after providing liquidity for WBTC-WETH pair in this example. But the liquidity is gone if we go to the other pages in the UNI web interface.

Below shows you have deposited in the ETH-WBTC pool:
![image](https://user-images.githubusercontent.com/35719445/96676965-2ff24100-13a1-11eb-8f3a-c6d85770865a.png)

Then if we go to https://app.uniswap.org/#/pool we see that the liquidity is no longer found.
![image](https://user-images.githubusercontent.com/35719445/96677158-98412280-13a1-11eb-868e-e946742f0124.png)

Our relevant account in https://info.uniswap.org/account/0x0xxxxxxxxxxxxx is also showing zero liquidity
![image](https://user-images.githubusercontent.com/35719445/96677326-f1a95180-13a1-11eb-8c5f-3060727ffa41.png)

Steps to reproduce:
1. Add liquidity in the https://app.uniswap.org/#/pool page.
2. Check that your pool share is now showing for the pair you have added liquidity for.
3. Deposit the LP tokens in https://app.uniswap.org/#/uni for the relevant pair.
4. Check that you are earning UNI in the same page.
5. Check again in https://app.uniswap.org/#/pool page and find that the liquidity is now zero.

**Comment by djreillo** [comment]
I would also like to expand on this.

Steps to reproduce:
1. Use the Add Liquidity in the https://app.uniswap.org/#/pool page.
2. Afterwards, check that you now have a pool share in the pair you have staked your tokens for and you have received your LP tokens.
3. Deposit your LP tokens in the relevant pair in the https://app.uniswap.org/#/uni page.
4. Afterwards, check that you are now earning UNI tokens in the same page.
![image](https://user-images.githubusercontent.com/35719445/96678333-143c6a00-13a4-11eb-92a4-9539d35832a3.png)
5. Check again in the https://app.uniswap.org/#/pool page and find that the liquidity is no longer showing.
![image](https://user-images.githubusercontent.com/35719445/96678409-3504bf80-13a4-11eb-936e-5de1ed43d68b.png)
The relevant account is now also showing $0 Liquidity.
![image](https://user-images.githubusercontent.com/35719445/96678451-4a79e980-13a4-11eb-9429-87b93e6e4bd5.png)

**Comment by moodysalem** [comment]
I believe this issue was fixed, but also the previous staking contracts are no longer relevant
