### ISSUE TITLE
NANJ-ETH on uni v1 decimal display issue

### ISSUE THREAD

**Issue by nardholio** [Uniswap/uniswap-interface#1124]
![image](https://user-images.githubusercontent.com/2659687/93937567-025c9e00-fcf6-11ea-8842-bafbbd20252b.png)

**Comment by platocrat** [comment]
I couldn't reproduce this locally nor on http://app.uniswap.org.ipns.localhost:8081/#/swap?use=v1 

@nardholio could you provide steps to reproduce the issue?

**Comment by platocrat** [comment]
Couldn't reproduce it on the regular non-IPFS URL at https://app.uniswap.org/#/swap?use=v1 either:

<img width="1025" alt="Screen Shot 2020-12-20 at 4 05 04 PM" src="https://user-images.githubusercontent.com/37757724/102725553-29b70d00-42dd-11eb-80ba-850758ce9f2a.png">

**Comment by JKirkYuan** [comment]
Hi! I took a look into this and reproduced the issue. After selecting a currency you get an overflow by entering a super big number for ETH (Note: it takes A LOT of zeros or any other random numbers)

Updating the ETH value
![image](https://user-images.githubusercontent.com/18089817/103145953-3aadb700-46ff-11eb-842c-ec25cfb10f34.png)

This seems an edge case since I feel it would be rare for a user to have that amount of ETH/other currency to swap. Also, this overflow will occur on any currency when updating the `From` value and the `To (estimated)` swap value will also stop converting.

Another example with 0xBitcoin
![image](https://user-images.githubusercontent.com/18089817/103146014-0edf0100-4700-11eb-81cd-8ebb708edfb8.png)

**Comment by MRHarrison** [comment]
@moodysalem what is seen as an acceptable fix here?

- Ellipsis with tooltip showing number
- Font resizing of number
- Wrap number but keep in container with no overlap of other text

**Comment by jochenboesmans** [comment]
Seems like displaying the number in scientific notation could be a solution (for example all numbers >10^12)
