### ISSUE TITLE
Governance address is fixed while the governor of the timelock can change

### ISSUE THREAD

**Issue by moodysalem** [Uniswap/uniswap-interface#1163]
**Bug Description**
If the governor alpha address changes, e.g. via proposal, the interface proposals UI will become outdated as it points to a fixed governor alpha address.

**Comment by dwrx** [comment]
Why do you consider it a bug? If someone proposed to change the governor contract, he should care to open PR to update the address also on UI. 

It can be dangerous to fetch it automatically or via oracle because there may be other active votings in the old governar contract on a different proposals. Moreover, we can even get a conflict in 2 different governor contracts while there are still active votings in the old one, and already new votings in the new contract. 

PS: as for the current voting on proposal & quorum thresholds, I think the best approach is to make them adjustable variables via governance voting, so in future we can higher these limits when the circulating supply will be much higher without the need to redeploy a contact again for every adjustment of these limits.

**Comment by moodysalem** [comment]
> Why do you consider it a bug? If someone proposed to change the governor contract, he should care to open PR to update the address also on UI.

Agree, but it could also always point at the timelock admin address (and assume the governance interface)

> It can be dangerous to fetch it automatically or via oracle because there may be other active votings in the old governor contract on a different proposals. Moreover, we can even get a conflict in 2 different governor contracts while there are still active votings in the old one, and already new votings in the new contract.

Active votings in the old governor contract are irrelevant after the timelock admin address changes, because they cannot effect any changes from the timelock address

**Comment by moodysalem** [comment]
The ideal solution for this would also preserve the proposal history of the previous governance contract (e.g. just hard code it)
