### ISSUE TITLE
TypeError: Cannot set property 'autoRefreshOnNetworkChange' of undefined

### ISSUE THREAD

**Issue by ligi** [Uniswap/uniswap-interface#1214]
sometimes I get a white screen with uniswap and see this error in the log

![Selection_287](https://user-images.githubusercontent.com/111600/99386800-525d7880-28d3-11eb-8292-c5329abecbf2.png)

**Comment by moodysalem** [comment]
might have something to do with brave + metamask (are you using metamask?), and it's this line
https://github.com/Uniswap/uniswap-interface/blob/03913d9c0b5124b95cff34bf2e80330b7fd8bcc1/src/index.tsx#L24

**Comment by moodysalem** [comment]
odd that the line would fail though, the previous line checks that `window.ethereum` exists.

**Comment by MicahZoltu** [comment]
The problem is that 
```ts
window.ethereum = undefined
assert('ethereum' in window === true)
```
Fixes:
```ts
if (window.ethereum !== undefined) {
	;(window.ethereum as any).autoRefreshOnNetworkChange = false
}
```
```ts
;(window.ethereum || {}).autoRefreshOnNetworkChange = false
```
I like the second one personally, but both are acceptable.  Since you know for certain that `window` is not undefined, and it is an object, you don't have to check `'ethereum' in window` first, you can skip straight to the undefined check.  A more thorough check would be something like `window.ethereum !== null && typeof window.ethereum === 'object'` if you really want to be certain.
