### ISSUE TITLE
Unnecessary trust assumptions with Cloudflare Insights and Google Analytics

### ISSUE THREAD

**Issue by JustinDrake** [Uniswap/uniswap-interface#1244]
The Uniswap interface dynamically loads JS payloads from `static.cloudflareinsights.com` and `www.google-analytics.com`:

https://static.cloudflareinsights.com/beacon.min.js
https://www.google-analytics.com/analytics.js

If either of these two domains is compromised (e.g. by a CloudFlare or Google rogue admin) malicious JS could dynamically run on the Uniswap interface and arbitrarily modify the Uniswap logic. (See for example [this line](https://github.com/Uniswap/uniswap-interface/blob/5a9a71ae2df230bac78ae5d1489bc3d96fe4783f/public/index.html#L42) which allows arbitrary execution of JS code from `static.cloudflareinsights.com`.) Malicious JS could lead to a loss of user funds.

It would be safer if the above two scripts `beacon.min.js` and `analytics.js` were statically pinned to IPFS as opposed to dynamically loaded from a trusted source. This would consolidate trust assumptions around the IPFS gateway as opposed to opening up the Uniswap interface to unnecessary attack vectors.

**Comment by moodysalem** [comment]
While true that these are existing trust assumptions, we are still depending the Cloudflare IPFS gateway (or any IPFS gateway) to serve the interface and specifically those JS bundles over HTTPS, meaning the trust assumption is necessary even if we pinned the bundles to IPFS. It is probably safer to assume that Cloudflare or Google will not serve malicious JS than an arbitrary IPFS gateway. 

The only trustless way to run the interface is locally, or via your own IPFS node, and you can use an ad blocker to prevent loading of those third party analytics providers.

**Comment by JustinDrake** [comment]
> the trust assumption is necessary even if we pinned the bundles to IPFS. It is probably safer to assume that Cloudflare or Google will not serve malicious JS than an arbitrary IPFS gateway.

* option A (status quo)—trust the IPFS gateway (cloudflare-ipfs.com) **and** Google Analytics (google-analytics.com) **and** Cloudflare Insights (cloudflareinsights.com)
* option B (my suggestion)—trust only the IPFS gateway (cloudflare-ipfs.com)

Option B is clearly strictly superior to option A in terms of trust assumptions.

**Comment by moodysalem** [comment]
> > the trust assumption is necessary even if we pinned the bundles to IPFS. It is probably safer to assume that Cloudflare or Google will not serve malicious JS than an arbitrary IPFS gateway.
> 
> * option A (status quo)—trust the IPFS gateway (cloudflare-ipfs.com) **and** Google Analytics (google-analytics.com) **and** Cloudflare Insights (cloudflareinsights.com)
> * option B (my suggestion)—trust only the IPFS gateway (cloudflare-ipfs.com)
> 
> Option B is clearly strictly superior to option A in terms of trust assumptions.

Uploading analytics scripts to IPFS may circumvent ad-blockers and tracker blockers, which I don't think we want to do. The best workaround here is to use an ad blocker or DNS level tracker blocker.

**Comment by MicahZoltu** [comment]
Option (B) also allows anyone running IPFS Companion extension or now anyone running Brave to no longer have to trust a centralized IPFS Gateway.  As more and more browsers implement IPFS support, more and more users will drop the implicit trust and centralization assumptions with option B, while under option A the implicit trust remains.

Generally speaking, I would like to see Uniswap prefer security and privacy over convenience.  One way to achieve this would be to simply remove the trackers from the page.  I know that this makes developing and iterating much harder, but it also respects user privacy.  Another option would be allowing users to opt-in to tracking, rather than tracking by default.  Finally, you could have the tracking get added by the edge server rather than served as part of the page so at least people running their own IPFS node and accessing the site directly via IPFS don't get served the trackers from centralized (and attackable) endpoints.
