### ISSUE TITLE
Position error in liquidity Pool

### ISSUE THREAD

**Issue by Kaz-Takagi** [Uniswap/uniswap-interface#1287]
**Bug Description**
I provided liquidity of approx. $310 worth of PROS/ETH and all transaction went well but my position on the liquidity pool is showing just $13 of PROS/ETH as per attached pic below.
It seemed that there was an error on the conversion rate between PROS and ETH when I provided the liquidity, and I guess that caused this error. Your support would be highly appreciated to get my crypto asset back. I can track all transaction on Etherscan.
![Screenshot_20210127-023616](https://user-images.githubusercontent.com/78042428/105886690-0acf3780-604e-11eb-9299-fc4c0563d825.png)

**Comment by ColetteXArt** [comment]
I have the same issue. With much larger pairs. #1133 can't see my LPs value and I see on Etherscan and everywhere else. Their support finally contacted me and told me to go on discord. They were SO rude. I have been a big supporter of Uniswap. But maybe they have so much liquidity, because no one can get it out...It's been 3 months @haydenadams @uniswap I hope you will contact me with more than go on discord?? I already have and all I hear are people with the same issue. Trust score on coingecko is a 6, this could be bad for @uniswap come on guys. The FTC will shut you down if you act like that. Whoever is answering info@uniswap.org is not nice or helpful in any way. with 1 Billion a day in transactions, they could offer some support for their community. I fixed the browser bug they hid the remove liquidity button, but then the site doesn't see the value of the LPs. So I looked on Zapper.fi and apy.vision you can use your LP contract and see it there and you may be able to swap it or pull out your funds. because my LPs are before the upgrade they need to be burned and pair with ETH or USDC in order to pull out liquidity.

**Comment by moodysalem** [comment]
Please ask in support channel of Discord.

**Comment by Kaz-Takagi** [comment]
> Please ask in support channel of Discord.

I did already but no help was provided there. That's why I came here. Your sincere support would be highly appreciated. The case is not closed at all.

**Comment by moodysalem** [comment]
> > Please ask in support channel of Discord.
> 
> I did already but no help was provided there. That's why I came here. Your sincere support would be highly appreciated. The case is not closed at all.

If you added liquidity at an incorrect price, and then somebody swapped to move the price of the pair to the correct price, there is nothing we can do. Uniswap does not set the price of a pair. It is set by the first liquidity provider, and then every liquidity provider after that adds at the current pair ratio. There is nothing _anyone_ can do to undo historical transactions on Ethereum, in general.

Discord is the platform we use for support and questions. GitHub is for documenting issues/bugs/features of the interface, and this is not one of those.
