### ISSUE TITLE
Add Liquidity - % increment buttons underflow error

### ISSUE THREAD

**Issue by mratsim** [Uniswap/uniswap-interface#1831]
**Bug Description**
Uniswap does not save the range

**Steps to Reproduce**

1. Go to https://app.uniswap.org/#/add/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/0xdB25f211AB05b1c97D595516F45794528a807ad8/500
2. Click on the minus or the plus button, for some cases the set range limit disappears
    ![image](https://user-images.githubusercontent.com/22738317/121342941-755c8200-c922-11eb-9dbe-99ee78eebbfd.png)
3. Look into the Javascript console
    `Failed to parse input amount: "0.81263" Error: fractional component exceeds decimals (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.2.0)`

**Expected Behavior**
I can set a range

**Comment by willhennessy** [comment]
Thanks for filing! To clarify "for some cases the set range limit disappears" - can you point me to the cases where this occurs?

**Comment by mratsim** [comment]
See my screenshot, USDC/EURS when clicking on any -0.1% or +0.1% button.

The issue is with the decimal library used in your frontend
> Failed to parse input amount: "0.81263" Error: fractional component exceeds decimals (fault="underflow", operation="parseFixed", code=NUMERIC_FAULT, version=bignumber/5.2.0)

**Comment by willhennessy** [comment]
I see, thanks. Refining the issue:

**Steps to reproduce**
1. Open https://app.uniswap.org/#/add/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/0xdB25f211AB05b1c97D595516F45794528a807ad8/500
2. Press -0.1% or +0.1% button -> nothing happens
3. Type in a min price value like 1.0 -> value populates in the field
4. Press -0.1% -> the value is erased from the field

Expected behavior:
- if the field is empty, the -0.1% button should enter a price value that is 0.1% below the current market price
- if the field is populated, the button should decrement that value by 0.1%

**Comment by willhennessy** [comment]
This will be fixed with the release of the new add liquidity ux
