### ISSUE TITLE
Uniswap Failed Txn - Request for refund for a failed transaction

### ISSUE THREAD

**Issue by Bvmech1989** [Uniswap/uniswap-interface#1861]
Dear sir, 

Txn were placed through uniswap but It became failed, i dont know why. 
Pl guide me what to do to get back my Eth or Elon.. 

Txn1 =0x848f11de83b03ae1be781e7d90ce4315a87b1cf6e66b3d4e753259facfcb42fd

You are requested to refund the amount of failed txn i will be very thankful to you

Thanks & Regards

Bharat

**Comment by willhennessy** [comment]
Hello sir, thanks for your question. Please check the customer support channel in the [Discord community](https://discord.com/invite/FCfyBSbCU5) for assistance. This github repo is intended for software bugs and new feature requests.

Please be aware that the Ethereum network processed your transaction up until the point of failure, and hence charged a gas fee for that work. The Ethereum network does NOT reimburse those fees when the transaction fails, because miners worked hard to process the tx up to the point of failure. This is fundamental to Ethereum and not something Uniswap can control.
