### ISSUE TITLE
Certain WalletConnect wallets don't broadcast transactions

### ISSUE THREAD

**Issue by paulrberg** [Uniswap/uniswap-interface#562]
**Bug Description**

WalletConnect (WC) only works with smart contract wallets. External accounts can only sign transactions via WC, but Uniswap doesn't handle the signed responses to broadcast them onto the blockchain.

**Steps to Reproduce**
1. Go to uniswap.exchange
2. Log in with an externally-owned account via Wallet Connect (Trust Wallet enables this)
3. Make a trade
4. Sign the trade

**Expected Behavior**
I would've expected the transaction to be broadcasted.

**Additional Context**
What I see in Trust Wallet (1 signed tx):

<img width="320" src="https://user-images.githubusercontent.com/8782666/70880509-ddeacd00-1fd1-11ea-9cf8-216efab04df8.PNG"/>

What I see on Uniswap (nothing):

<img width="1024" alt="Capture d’écran 2019-12-16 à 07 00 16" src="https://user-images.githubusercontent.com/8782666/70880513-e17e5400-1fd1-11ea-9c82-7f387229cd16.png">

**Comment by NoahZinsmeister** [comment]
Hi @PaulRBerg , I can confirm that I can replicate this behavior. It's pretty curious, as other WC wallets which use EOAs (e.g. Rainbow) correctly broadcast transactions when connected to Uniswap. So I think this is a Trust-specific issue, I'll bring it to their attention. Thanks for the report!

**Comment by PaulRBerg** [comment]
Interesting. Trust uses a different blockchain provider (Alchemy). Maybe it has to do with that?

Cc-ing @vikmeup.

**Comment by vikmeup** [comment]
Main responsibility of:
- Wallet Connect: is to establish communication between Wallet and DApp
- Wallet: Sign Provided payload/transaction via WalletConnect
- DApp: Handle signed payload/transaction

It's important every piece only does what is responsible for.

**Example:**
Here is an example. Imagine user wants to swap ERC20 <> ETH, in first transaction you need to set allowances and then swap, in total this is two transactions. 

What if user only confirm one transaction and rejects the second one? then wallet broadcasted transaction that DApp did not expect it to do it, because DApp responsibility to collect two transactions before broadcasting them into the network.

Since nodes could be different and transaction might not be always available on correct node, it's always suggested to use same node for broadcast/checking transaction status.

This is the same reason why MetaMask will stop injecting web3, because it needs to be responsible only for signing and not the rest of the business logic and dependency.

**Comment by vikmeup** [comment]
There is two actions:
```
eth_signTransaction 
eth_sendTransaction
```

In the case of `eth_sendTransaction` - it should be broadcasted, if it's not we need to look into Alchemy how it handles broadcast

**Comment by moodysalem** [comment]
Worth exploring changing the app to always use Infura for data, and only use the injected provider/wallet connect for signing. By splitting up the wallet and provider interface, we would end up with a cleaner architecture. This would make the app harder to use for a testnet unless we also added a setting to switch networks/change the ETH node used for data & broadcasting signed transactions.
