### ISSUE TITLE
Support Ethereum Classic

### ISSUE THREAD

**Issue by hitchcott** [Uniswap/uniswap-interface#861]
It appears that Uniswap already supports multiple networks (Kovan, Mainnet, etc.), so I assume it would be fairly straight forward to add support for ETC (and its ERC20 tokens such a WETH).

ETC has recently hard-forked to enable 1:1 contract compatibility, which would make deploying the contracts simple. 

In terms of wallet integrations, Metamask supports ETC natively.

The frontend would need to be upgraded to support ETC, I assume. 

Rather than having to maintain a separate fork just for ETC, it would be awesome to get this integrated in to the main frontend.

Is this something that is likely to be approved? If so, I would be happy to contribute a PR.

**Comment by tpmccallum** [comment]
I have a script to deploy both V1 and V2 on an alternative Ethereum compatible network.
Contracts are working ... almost have this front-end interface working aside from a couple of issues; one of which is as follows.

I get a js error `Cannot read property "address" of undefined`

This error relates to the `useWETHContract` function at line 49 of the `useContract.ts` file [1].

```
export function useWETHContract(withSignerIfPossible?: boolean): Contract | null {
  const { chainId } = useActiveWeb3React()
  return useContract(chainId ? WETH[chainId].address : undefined, WETH_ABI, withSignerIfPossible)
}
```
The reason for this error would be the fact that the WETH smart contract is not deployed on this alternative network. I am unable to resolve this because I am not sure which WETH contract it expects. 

I only have the WETH ABI [2] (not the source code or bytecode) and therefore can not deploy the WETH contract to resolve this issue.

@moodysalem could you please assist by providing an address to the WETH contract on the ETH mainnet? Thanks in advance.


[1] https://github.com/Uniswap/uniswap-interface/blob/master/src/hooks/useContract.ts#L49
[2] https://github.com/Uniswap/uniswap-interface/blob/master/src/constants/abis/weth.json

**Comment by tpmccallum** [comment]
Oh, I think I just found it
https://etherscan.io/token/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2

**Comment by tpmccallum** [comment]
I think that one of the main hurdles for an established chain like ETC (with a chainId of 62) will be supplying the Uniswap Interface with sufficient config changes. For example one of Uniswap Interface's Node.js dependencies `@uniswap/sdk` [3] has chainId and Uniswap Factory [4] deployment address baked in. 

[3] https://github.com/Uniswap/uniswap-sdk/blob/v2/src/constants.ts#L6
[4] https://github.com/Uniswap/uniswap-sdk/blob/v2/src/constants.ts#L25

**Comment by moodysalem** [comment]
> I think that one of the main hurdles for an established chain like ETC (with a chainId of 62) will be supplying the Uniswap Interface with sufficient config changes. For example one of Uniswap Interface's Node.js dependencies `@uniswap/sdk` [3] has chainId and Uniswap Factory [4] deployment address baked in. 
> 
> 
> 
> [3] https://github.com/Uniswap/uniswap-sdk/blob/v2/src/constants.ts#L6
> 
> [4] https://github.com/Uniswap/uniswap-sdk/blob/v2/src/constants.ts#L25

You are right, we would have to sign all the transactions from the same deployment address to get the same addresses. But this is predicated on deciding to support ETC. I have no issue with it. @NoahZinsmeister

**Comment by tpmccallum** [comment]
Thanks @moodysalem 
Incredible job on this interface btw!

Would uniswap interface consider the following config proposal; a high level JSON config file such as the following example?

```
{
	"rpc_endpoint": "",
	"chain_id": "",
	"contract_addresses": {
		"uniswap_v1_factory": "",
		"uniswap_v1_exchange_template": "",
		"uniswap_v2_factory": "",
		"uniswap_v2_multicall": "",
		"uniswap_v2_migrator": "",
		"uniswap_v2_router": "",
		"uniswap_v2_ens_registry": "",
		"uniswap_v2_unisocks": ""
	}
}
```
This would allow uniswap interface to essentially be deployed on any Ethereum compatible blockchain. I realise that this would not provide any immediate benefit to the ETH network where token trading is most prevalent. However, with trusted bridges between blockchain networks now on the horizon it would allow Uniswap to remain the application of choice for token trading on other Ethereum compatible networks. I would be very happy to assist with these changes. Please let me know what your thoughts are around this.
