### ISSUE TITLE
add useGasEstimate hook to proactively disable buttons + show errors

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-interface#872]

**Comment by moodysalem** [comment]
tried this UI, but it's not that good because of inconsistencies between infura nodes + inconsistency between UI data and infura node data, which can result in failures where not valid.

instead we should surface useful error messages when we can't estimate gas at confirm swap time. going to do this by using eth_call and translating revert reasons

**Comment by moodysalem** [comment]
closed in favor of #871
