### ISSUE TITLE
allow slippage to be set via URL parameter

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-interface#876]
this is potentially dangerous as users could be tricked into trading at high slippage.

one solution is bounding the range from e.g. 0-2%, another is showing some type of UI.

**Comment by realrouse** [comment]
I agree that there should be a warning in the UI if the slippage is extremely high, to avoid scams.

Slippage set via URL Parameter would really benefit the usability for many FoT/Deflationary tokens like BSOV https://github.com/Uniswap/uniswap-frontend/issues/836 (which has 1% Fee-on-Transfer) who integrate Uniswap directly in their websites using iFrame, before they are officially listed on Uniswap.

Is there anyone who wishes to develop this and be assigned to this issue? I can give you some BSOV for it, too :) let me know! @NoahZinsmeister  Thank you for developing the last issue regarding FoT-tokens so quickly.

**Comment by realrouse** [comment]
Is this issue planned to be solved in the near future? BSOV is getting more trading activity and liquidity now ( BSOV-ETH: https://uniswap.info/pair/0xfac49a3524a99c90defb63571b2dfff70d12b1e2), so it would be best if the Price Slippage Tolerance could be automatically set through our links and Uniswap Iframe at https://bsov.io/trade
Thank you!

**Comment by moodysalem** [comment]
Unlikely to happen, because slippage is a risky setting to modify, and it's currently set and saved at the app level. We could enable a one-time override via URL but that is also a dangerous feature without significant warnings. Token lists might include additional metadata to indicate fee on transfer via `extensions`, which could then be used in the app to show minimum slippage for certain tokens.
